name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear description of the bug.
  - type: input
    id: version
    attributes:
      label: CitySense version
      placeholder: 0.2.0
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: 3.12
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. citysense pilot init fi
        2. citysense query "..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true
